
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_tensors_matmul.ipynb


import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['image.cmap'] = 'gray'
import torch
from torch import tensor
import graphviz
import os



import pandas as pd
import operator
from fastai import datasets
import gzip
import pickle



os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz/bin/'

def test(a, b, comp, cname=None):
    if cname is None: cname = comp.__name__
    assert comp(a,b), f"{cname}: \n{a} \b{b}"

def test_eq(a,b):
    test(a,b, operator.eq, "==")

def gv(s): return graphviz.Source('digraph G{ rankdir="LR"' + s + '; }')

def near(a,b):
    """Test if two tensors are nearly identical"""
    return torch.allclose(a,b, rtol=1e-03, atol=1e-05)

def test_near(a,b):
    test(a,b, near)