
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_fully_connected.ipynb


from exp.nb_01 import *

import gzip
import pickle
import torch
import math

from fastai import datasets
from torch import tensor
from torch.nn import init

import torch.nn as nn
import matplotlib.pyplot as plt

def get_data():
    path = datasets.download_data('http://deeplearning.net/data/mnist/mnist.pkl', ext='.gz')
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train,y_train,x_valid,y_valid))

def normalize(x,m,s): return (x-m)/s

def get_stats(a): return f"Mean: {a.mean()}  STD: {a.std()}"

def test_near_zero(a, tol=1e-02): assert a.abs()<tol, f"Near zero: {a}"